site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Hausenblas'
docs_dir: docs/
repo_name: 'joaompinto/hobbykube'
repo_url: 'https://github.com/joaompinto/hobbykube'
nav:
    - Home: index.md
theme:
  name: 'material'